version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.0
    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - run: npm install
      - run: npm test
